add_subdirectory(01_hello)
add_subdirectory(02_sleep)
add_subdirectory(03_return_value)
add_subdirectory(04_co_spawn)
add_subdirectory(05_tcp_server)
add_subdirectory(06_tcp_client)
add_subdirectory(07_receive_stream)
add_subdirectory(08_line_protocol)
add_subdirectory(09_stop_then)
add_subdirectory(10_timeout)
add_subdirectory(11_error_handling)
add_subdirectory(12_when_all)
add_subdirectory(13_when_any)
add_subdirectory(14_all_any)
add_subdirectory(15_channel)
add_subdirectory(16_channel_pipe)
add_subdirectory(17_scatter_gather)
add_subdirectory(18_zero_copy)
add_subdirectory(19_buffer_ring)
add_subdirectory(20_threading)
add_subdirectory(21_benchmark)
