add_executable(tutorial.21_benchmark main.cpp)
target_link_libraries(tutorial.21_benchmark blog)
target_compile_features(tutorial.21_benchmark PRIVATE cxx_std_23)

add_executable(tutorial.21_post post.cpp)
target_link_libraries(tutorial.21_post blog asio::asio)
target_compile_features(tutorial.21_post PRIVATE cxx_std_23)


add_executable(tutorial.21_network_asio network_asio.cpp)
target_link_libraries(tutorial.21_network_asio blog asio::asio)
target_compile_features(tutorial.21_network_asio PRIVATE cxx_std_23)

add_executable(tutorial.21_network_asio_uring network_asio.cpp)
target_compile_definitions(tutorial.21_network_asio_uring PRIVATE ASIO_HAS_IO_URING ASIO_DISABLE_EPOLL)
target_link_libraries(tutorial.21_network_asio_uring blog asio::asio PkgConfig::liburing)
target_compile_features(tutorial.21_network_asio_uring PRIVATE cxx_std_23)

add_executable(tutorial.21_network_tpc network_tpc.cpp)
target_link_libraries(tutorial.21_network_tpc blog)
target_compile_features(tutorial.21_network_tpc PRIVATE cxx_std_23)

add_executable(tutorial.21_network_tpc_local_buf network_tpc_local_buf.cpp)
target_link_libraries(tutorial.21_network_tpc_local_buf blog)
target_compile_features(tutorial.21_network_tpc_local_buf PRIVATE cxx_std_23)

add_executable(tutorial.21_network_tpc_zc network_tpc_zc.cpp)
target_link_libraries(tutorial.21_network_tpc_zc blog)
target_compile_features(tutorial.21_network_tpc_zc PRIVATE cxx_std_23)

add_executable(tutorial.21_network_client network_client.cpp)
target_link_libraries(tutorial.21_network_client blog)
target_compile_features(tutorial.21_network_client PRIVATE cxx_std_23)